### ISSUE TITLE
QuestionnaireResponse _include

### ISSUE THREAD

**Issue by ckundra** [argonautproject/questionnaire#1]
In section 2.6.2 of the [IG](https://argonautproject.github.io/questionnaire/guidance.html), we've added a query parameter (_include) to tell the Answer Bank server to include in the Questionnaire in the QuestionnaireResponse resource response.

What will the QuestionnaireResponse resource look like if the Questionnaire is included?

**Comment by Healthedata1** [comment]
This would return as a Bundle
