### ISSUE TITLE
QuestionnaireResponse Patient search

### ISSUE THREAD

**Issue by ckundra** [argonautproject/questionnaire#2]
In section 2.62. of the [IG](https://argonautproject.github.io/questionnaire/guidance.html), we've added the ability to search "based on a patient encounter".

> GET [base]/QuestionnaireResponse/?status=completed&patient=Patient/[patient]&context=Encounter/[encounter]

**Questions**

1. Should we be making it a requirement or a disclaimer that the Patient and Encounter resources must be "contained" in order for this search to work?

2. Is there value to outlining a more broad "patient" search (without context)?
> GET [base]/QuestionnaireResponse/?status=completed&patient=Patient/[patient]

**Comment by Healthedata1** [comment]
agree that getting multiple QR for  a single patient

**Comment by Healthedata1** [comment]
#### the mentioned example is:

`GET [base]/QuestionnaireResponse/?status=completed&patient=Patient/[patient]&context=Encounter/[encounter]`   

the search prerequisites are that the client knows the Patient/id and Encounter/id through a discovery process.  The Answer-Bank would return the QR resource based on these parameters without needing to have access to the FHIR Patient or Encounter endpoint.

#### A simpler and friendlier approach would be by Patient name and dates.  Or to get all answers for patient via the patient name.  

This would require: 

1.  doing two searched - 1 on patient and 1 on QA.  or
1.  a single search using a [chained parameter](http://hl7.org/fhir/search.html#chaining) which may lead to the cross servers search issues. if your answer bank only contained the QR resource. 

an example for getting all QRs for patients named would be ....

`GET [base]/QuestionnaireResponse/?status=completed&patient.name=peter`

**Comment by Healthedata1** [comment]
Another alternative is to use "opaque identifiers" to reference the subject instead of a reference to a patient ID.  

From the current specification:

"References are also allowed to have an identifier. The modifier :identifier allows for searching by the identifier rather than the literal reference:

 `GET [base]/Observation?subject:identifier=http://acme.org/fhir/identifier/mrn|123456`

This is a search for all observations that reference a patient by a particular patient MRN. When the :identifier modifier is used, the search value works as a _token_ search. "

**Comment by Healthedata1** [comment]
If we choose to support searching on a Reference.identifier,  we will have to define/ extend the search parameter for 3.0.1.

**Comment by Healthedata1** [comment]
see follow-up discussion on [Zulip](https://chat.fhir.org/#narrow/stream/4-implementers/subject/How.20search.20on.20Reference.2Eidentifier.20in.20STU3)

**Comment by Healthedata1** [comment]
discussed at WGM and added contained P to profile for these searches
