### ISSUE TITLE
What do item order extensions look like and mean?

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#47]
https://argonautproject.github.io/questionnaire/StructureDefinition-extension-itemOrder.html describes an "order" extension. Some issues to address:

1. I'm confused on motivation I couldn't follow the explanation that "However, this is impossible to validate."
2. Do the order values need to be non-negative? Is zero allowed? Do values need to be consecutive, or can there be gaps?

**Comment by Healthedata1** [comment]
Hmm I thought I edited the text - will add more guidance.   thanks

**Comment by Healthedata1** [comment]
Add to the documentation. 

change text to "However this is, in practice, difficult to validate." 

'The order values should be non-negative consecutive integers starting at 0 or 1.
