### ISSUE TITLE
Workflow image appears "squished"

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#49]
![image](https://user-images.githubusercontent.com/313089/53126034-e47cf500-3524-11e9-95e1-adc29d1a1e25.png)

**Comment by Healthedata1** [comment]
I will try to stretch vertically but this how I made it  :(

**Comment by jmandel** [comment]
Overall, would be good to include all source materials for images in the guide; what tool did you use for this?

**Comment by Healthedata1** [comment]
the source images were ppt slides which I lost in my own clean.sh debacle a few months back.. Will redraw.   
How should they be shared in the IG  ( folder  are they linked to the image?)  Can you point to an example?

**Comment by jmandel** [comment]
To start, you can just include a ppt deck in the repo, like in an "images/source" directory.

**Comment by jmandel** [comment]
Then it'd be good to also do http://www.thepowerpointblog.com/powerpoint-svg/ to export slides to svg instead of pngs.

**Comment by Healthedata1** [comment]
done.  although not able to use the refernce above.  created in google sheets and downloaded svg and ppt to ig.
