### ISSUE TITLE
questionnaire_example_sampler dateTime

### ISSUE THREAD

**Issue by ckundra** [argonautproject/questionnaire#5]
Hi Eric,
I noticed that in the sampler, the type is incorrect on the dateTime example... it is 'date' while it should be 'dateTime'.

Thanks!
Chris

> 
> {
>             "linkId": "g6",
>             "prefix": "5. ",
>             "text": "dateTime",
>             "type": "group",
>             "required": true,
>             "item": [
>               {
>                 "extension": [
>                   {
>                     "url": "http://fhir.org/guides/argonaut-questionnaire/StructureDefinition/extension-score",
>                     "valueDecimal": 3
>                   }
>                 ],
>                 "linkId": "g6.q1",
>                 "text": "If a laden swallow left Camelot on 7/5/2018 and noon when would it reach Castle Anthrax?",
>                 **"type": "date",**
>                 "required": true,
>                 "repeats": false
>               }
>             ]
>           }

**Comment by Healthedata1** [comment]
fixed,  will update in test renderer next time AWS is updated
