### ISSUE TITLE
Footnote 4 appears misplaced

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#50]
Body text reads:

> The server selects the following items optimized for the outcome of the assessment or testee’s estimated ability or trait (4)
![image](https://user-images.githubusercontent.com/313089/53126124-13936680-3525-11e9-8c75-d6204cec85bb.png)

But the footnote is unrelated:

> 4. https://en.wikipedia.org/wiki/Questionnaire ↩

**Comment by Healthedata1** [comment]
the link were I pulled this definition.   maybe use the HealthMeasures definition instead

**Comment by Healthedata1** [comment]
added 'source" to footnote
