### ISSUE TITLE
Images in adaptive questionnaire are squished

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#51]
![image](https://user-images.githubusercontent.com/313089/53126343-87ce0a00-3525-11e9-886d-330715b8fe6f.png)

(and there are stray "." characters interspersed.)

**Comment by Healthedata1** [comment]
the stray .  are a known rendering artifact I can seem to chase down.  Investigate the images.  may need to redo.

**Comment by jmandel** [comment]
For images, some text is unreadable too. Would be better to export all images as `.svg` instead of `.png` so they don't lose quality.

**Comment by Healthedata1** [comment]
I don't know how to use svg in bootstrap/jekyll.   I lost the originals in my own clean.sh debacle.   Will bite the bullet and recreate and use higher res pictures.

**Comment by jmandel** [comment]
You can use svg just like a png or jpg in jekyll.

**Comment by Healthedata1** [comment]
done using Google sheets which saves as svg.
