### ISSUE TITLE
Dynamic form scoring example inconsistent with description

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#52]
I can't follow what's happening in the scoring example at https://argonautproject.github.io/questionnaire/adaptive.html. The explanatory text states: 

> The service may calculated and record score in the QuestionnaireResponse resource as “answers” to a “score” question itme in the Questionnaire

(note typo in "itme" -- global spell-check would be good)

But in the example, the score is conveyed within the contained `Questionnaire` rather than in a `QuestionnaireResponse` item:

```js
   {
        "linkId": "g4",
        "type": "group",
        "item": [
          {
            "extension": [
              {
                "url": "http://fhir.org/guides/argonaut-questionnaire/StructureDefinition/extension-hidden",
                "valueBoolean": true
              }
            ],
            "linkId": "g3.q1",
            "text": "The total score is:",
            "type": ,
            "required": true,
            "repeats": false,
            "readOnly": true,
            "initialQuantity": {
              "value" : 24,
              "unit" : "points",
              "system" : "http://unitsofmeasure.org",
              "code" : "\{score\}"
            }
          }
```

A few issues here:

* The linkID should probably say `g4.q1` instead of `g3.q1`
* I don't think there should be backslashes in front of the braces in the `\{score\}` value.
* the quantity "24 points" should be conveyed as a `QuestionnaireResponse` item, if I understood the explanatory text correctly

**Comment by Healthedata1** [comment]
will fix - the example predated updated workflow.

**Comment by Healthedata1** [comment]
updated example to be congruent with descriptiion
