### ISSUE TITLE
Invalid JSON and inconsistent indentation make examples hard to read

### ISSUE THREAD

**Issue by jmandel** [argonautproject/questionnaire#53]
For example in the following snippet:

* JSON properties aren't consistently indented
* comment markers render incorrectly (you can mark these blocks as "javascript" instead of "json" template to prevent the red error highlighting)

![image](https://user-images.githubusercontent.com/313089/53127147-69690e00-3527-11e9-851c-9ec582a04660.png)

**Comment by Healthedata1** [comment]
I tried this out using json highlighting show the inline comments...  I think they are hard to read otherwise.  but it looks like its too distracting.  will remove add user instruction on inline comments instead

**Comment by Healthedata1** [comment]
removed highlighting,
udpated example and linkID to reflect guidance
added note" Note that these json examples are annotated with nonstandard comments and snipped for brevity."
the UCUM unit is '{score}' and hence the escape characters.
