### ISSUE TITLE
Section 1.6 Assumptions and Preconditions

### ISSUE THREAD

**Issue by ckundra** [argonautproject/questionnaire#57]
The SMART links go to smarthealthit.org... which then links to the officially published HL7 guidance.  Perhaps we link directly to the HL7 pages to save users a click.

Also the US Core General Guidance link is broken (missing a slash before "guidance.html").  It should be
http://hl7.org/fhir/us/core/guidance.html

**Comment by Healthedata1** [comment]
fixed
