### ISSUE TITLE
Parser error in Questionnaire-questionnaire-example-phq9.xml file

### ISSUE THREAD

**Issue by JohnLHook** [argonautproject/questionnaire#60]
I downloaded https://www.fhir.org/guides/argonaut/questionnaire/examples.xml.zip file. When I open the Questionnaire-questionnaire-example-phq9.xml file Oxygen reports: "Element type "img" must be followed by either attribute specifications, ">" or "/>"."

**Comment by Healthedata1** [comment]
Thanks for the heads up.  The publisher did not catch it but there is no space between the " and the 'alt' attribute which is causing the xml editor errors ( get similar error in XMLSpy)  I will correct in the CI Build.
