### ISSUE TITLE
error loading implementation guide

### ISSUE THREAD

**Issue by JohnLHook** [argonautproject/questionnaire#66]
When I attempt to load the IG into the FHIR validator I get the following error.

```
D:\Downloads\FHIR>java -jar org.hl7.fhir.validator.jar c:\temp\ArgoQuest.xml -version 3.0 -ig http://fhir.org/guides/argonaut/questionnaire/StructureDefinition/argo-questionnaire
FHIR Validation tool Version 4.2.3-SNAPSHOT (Git# f1dc0e57541b). Built 2020-02-25T09:40:12.571+11:00 (3 days old)
Detected Java version: 1.8.0_191 from C:\Program Files\Java\jre1.8.0_191 on amd64 (64bit). 14423MB available
Arguments: c:\temp\ArgoQuest.xml -version 3.0 -ig http://fhir.org/guides/argonaut/questionnaire/StructureDefinition/argo-questionnaire
Directories: Current = D:\Downloads\FHIR, Package Cache = C:\Users\jlhook\.fhir\packages
  .. FHIR Version 3.0, definitions from hl7.fhir.r3.core#3.0.2
  .. connect to tx server @ http://tx.fhir.org
    (v3.0.2)
+  .. load IG from http://fhir.org/guides/argonaut/questionnaire/StructureDefinition/argo-questionnaire
   ..Detect format for http://fhir.org/guides/argonaut/questionnaire/StructureDefinition/argo-questionnaire
[Fatal Error] :25:1: Content is not allowed in prolog.
Exception in thread "main" java.lang.Exception: Unable to find/resolve/read -ig http://fhir.org/guides/argonaut/questionnaire/StructureDefinition/argo-questionnaire

```

When I attempt to open the url directly I get the following response.

> You should not be seeing this page. If you do, PHP has failed badly. 

Is something not right?

**Comment by Healthedata1** [comment]
I have not tried this use of the validator. The prolog error makes me think
is using JSON and expecting XML.

Eric

Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by JohnLHook** [comment]
Eric,

I was attempting to set up the validator so that I can validate some questionnaires against the Argonaut profile. I was trying to follow the instructions at https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Validatingagainstanimplementationguide

If I'm doing something wrong, please let me know.

Thanks
John

**Comment by JohnLHook** [comment]
Eric,

I was attempting to set up the validator so that I can validate some questionnaires against the Argonaut profile. I was trying to follow the instructions at https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Validatingagainstanimplementationguide

If I'm doing something wrong, please let me know.

Thanks
John
